spring:
  profiles:
    active: user
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/jujia?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password:
    tomcat:
      max-idle: 10
      max-wait: 10000
      min-idle: 5
      initial-size: 5
  main:
    allow-bean-definition-overriding: true #当遇到同样名字的时候，是否允许覆盖注册
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#公共配置与profiles选择无关
mybatis:
  typeAliasesPackage: com.spring.web.dao
  mapperLocations: classpath:mapper/*.xml
server:
  port: 8081
  servlet:
    session:
      timeout: 10
  tomcat:
    uri-encoding: utf-8

